// verity-go/metadata/cross_test.go
// Cross-language round-trip tests.
//
// These tests embed binary data generated by the Rust implementation to verify
// that the Go code can correctly deserialize Rust-produced FlatBuffers, and vice versa.
//
// To update the Rust fixture:
//  1. Run: cargo test --package cryptpilot-verity -- test_cross_serialize --nocapture
//  2. The test prints base64-encoded serialized bytes to stdout
//  3. Paste the base64 string into rustFixtureBase64 below
//
// To update the Go fixture (for the Rust side):
//  1. Run: go test ./metadata/ -v -run TestCross_GoSerialize
//  2. The test prints base64-encoded serialized bytes to stdout
//  3. Paste into the Rust test's go_fixture_base64 constant
package metadata

import (
	"encoding/base64"
	"testing"
)

// rustFixtureBase64 is a base64-encoded FlatBuffers Metadata binary produced by
// the Rust serialize_metadata() function. It contains:
//   - 3 files: "a.txt" (data: "hello"), "b.txt" (data: "world"), "c.txt" (data: "")
//   - labels: {"env": "prod", "version": "1.0"}
//
// Generated by: cryptpilot-verity Rust implementation.
// To regenerate, see instructions at top of this file.
const rustFixtureBase64 = "" // TODO: paste base64 from Rust when available

// TestCross_DeserializeRustMetadata verifies that Go can deserialize metadata
// produced by the Rust implementation.
func TestCross_DeserializeRustMetadata(t *testing.T) {
	if rustFixtureBase64 == "" {
		t.Skip("rustFixtureBase64 not set — run Rust test to generate")
	}

	data, err := base64.StdEncoding.DecodeString(rustFixtureBase64)
	if err != nil {
		t.Fatalf("decode base64: %v", err)
	}

	info, err := DeserializeMetadata(data)
	if err != nil {
		t.Fatalf("deserialize: %v", err)
	}

	// Verify expected content
	if len(info.FileInfos) != 3 {
		t.Errorf("expected 3 files, got %d", len(info.FileInfos))
	}

	// Verify sorted order
	expectedPaths := []string{"a.txt", "b.txt", "c.txt"}
	for i, fi := range info.FileInfos {
		if fi.Path != expectedPaths[i] {
			t.Errorf("file[%d].path: expected %q, got %q", i, expectedPaths[i], fi.Path)
		}
	}

	// Verify labels
	if info.Labels["env"] != "prod" {
		t.Errorf("labels[env]: expected prod, got %q", info.Labels["env"])
	}
	if info.Labels["version"] != "1.0" {
		t.Errorf("labels[version]: expected 1.0, got %q", info.Labels["version"])
	}

	// Verify each file's integrity
	for i, fi := range info.FileInfos {
		if err := fi.VerifySelf(); err != nil {
			t.Errorf("file[%d] (%s) verification failed: %v", i, fi.Path, err)
		}
	}
}

// TestCross_GoSerialize serializes known test data and prints base64 output.
// The printed base64 should be pasted into the Rust test's go_fixture_base64.
func TestCross_GoSerialize(t *testing.T) {
	// Create test file info matching the Rust fixture
	fileInfos := []FileVerityInfo{
		makeTestFileVerityInfo("a.txt", []byte("hello")),
		makeTestFileVerityInfo("b.txt", []byte("world")),
		makeTestFileVerityInfo("c.txt", []byte("")),
	}
	labels := map[string]string{
		"env":     "prod",
		"version": "1.0",
	}

	serialized, err := SerializeMetadata(fileInfos, labels)
	if err != nil {
		t.Fatalf("serialize: %v", err)
	}

	// Verify round-trip
	info, err := DeserializeMetadata(serialized)
	if err != nil {
		t.Fatalf("deserialize own output: %v", err)
	}

	if len(info.FileInfos) != 3 {
		t.Errorf("expected 3 files, got %d", len(info.FileInfos))
	}

	// Verify descriptor hashes are consistent
	for _, fi := range info.FileInfos {
		if err := fi.VerifySelf(); err != nil {
			t.Errorf("verify %s: %v", fi.Path, err)
		}
	}

	// Print base64 for Rust side to consume
	t.Logf("Go serialized metadata (base64 for Rust test):\n%s",
		base64.StdEncoding.EncodeToString(serialized))
}

// TestCross_MetadataHash verifies that the metadata hash calculation produces
// a deterministic result for the same input.
func TestCross_MetadataHash(t *testing.T) {
	fileInfos := []FileVerityInfo{
		makeTestFileVerityInfo("a.txt", []byte("hello")),
		makeTestFileVerityInfo("b.txt", []byte("world")),
	}
	labels := map[string]string{"key": "value"}

	serialized, err := SerializeMetadata(fileInfos, labels)
	if err != nil {
		t.Fatalf("serialize: %v", err)
	}

	hash1, err := CalculateMetadataHash(serialized)
	if err != nil {
		t.Fatalf("hash 1: %v", err)
	}

	// Deserialize and re-serialize
	info, err := DeserializeMetadata(serialized)
	if err != nil {
		t.Fatalf("deserialize: %v", err)
	}

	serialized2, err := SerializeMetadata(info.FileInfos, info.Labels)
	if err != nil {
		t.Fatalf("re-serialize: %v", err)
	}

	hash2, err := CalculateMetadataHash(serialized2)
	if err != nil {
		t.Fatalf("hash 2: %v", err)
	}

	if hash1 != hash2 {
		t.Errorf("hash not deterministic: %s != %s", hash1, hash2)
	}

	t.Logf("Metadata hash: %s", hash1)
}
