// verity-go/metadata/interop_test.go
package metadata

import (
	"bytes"
	"encoding/hex"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"testing"

	"github.com/openanolis/cryptpilot/verity-go/verity"
)

// expectedDescriptorHashes maps test file name to expected SHA-256 descriptor hash.
// Copied from verity-core/src/digest.rs tests (lines 538-551).
var expectedDescriptorHashes = map[string]string{
	"empty":                 "3d248ca542a24fc62d1c43b916eae5016878e2533c88238480b26128a1f1af95",
	"onebyte":               "9845e616f7d2f7a1cd6742f0546a36d2e74d4eb8ae7d9bdc0b0df982c27861b7",
	"oneblock":              "3fd7a78101899a79cd337b1b4e5414be8bcb376b133370156ef6e65026d930ed",
	"oneblockplusonebyte":   "c0b9455d545b6b1ee5e7b227bd1ed463aaa530a4840dcd93465163a2b3aff0da",
	"hashblock_-1_0":        "c4b519068d8c8c68fd5e362fc3526c5b11e15f8eb72d4678017906f9e7f2d137",
	"hashblock_-1_-1":       "7aa0bb537c623562f898386ac88acd319267e4ab3200f3fd1cf648cfdb4a0379",
	"hashblock_-1_1":        "f804e9777f91d3697ca015303c23251ad3d80205184cfa3d1066ab28cb906330",
	"hashblock_0_0":         "f5c2b9ded1595acfe8a996795264d488dd6140531f6a01f8f8086a83fd835935",
	"hashblock_0_-1":        "5c00a54bd1d8341d7bbad060ff1b8e88ed2646d7bb38db6e752cd1cff66c0a78",
	"hashblock_0_1":         "a7abb76568871169a79104d00679fae6521dfdb2a2648e380c02b10e96e217ff",
	"hashblock_1_0":         "09510d2dbb55fa16f2768165c42d19c4da43301dfaa05705b2ecb4aaa4a5686a",
	"hashblock_1_-1":        "26159b4fc68c63881c25c33b23f2583ffaa64fee411af33c3b03238eea56755c",
	"hashblock_1_1":         "57bed0934bf3ab4610d54938f03cff27bd0d9d76c9a77e283f9fb2b7e29c5ab8",
}

// expectedPaths is the sorted list of file names from make_testfiles.py.
var expectedPaths = []string{
	"empty",
	"hashblock_-1_-1",
	"hashblock_-1_0",
	"hashblock_-1_1",
	"hashblock_0_-1",
	"hashblock_0_0",
	"hashblock_0_1",
	"hashblock_1_-1",
	"hashblock_1_0",
	"hashblock_1_1",
	"oneblock",
	"oneblockplusonebyte",
	"onebyte",
}

// fixtureDir returns the directory containing test fixtures.
func fixtureDir() string {
	_, filename, _, _ := runtime.Caller(0)
	return filepath.Join(filepath.Dir(filename), "testdata")
}

// TestInterop_DeserializeRustMetadata loads a metadata file generated by the Rust CLI
// and verifies all fields using Go's implementation.
func TestInterop_DeserializeRustMetadata(t *testing.T) {
	fbPath := filepath.Join(fixtureDir(), "rust.metadata.fb")
	data, err := os.ReadFile(fbPath)
	if err != nil {
		if os.IsNotExist(err) {
			t.Skip("fixture not found — run `make gen-interop-fixture` first")
		}
		t.Fatalf("read fixture: %v", err)
	}

	info, err := DeserializeMetadata(data)
	if err != nil {
		t.Fatalf("deserialize: %v", err)
	}

	// Verify file count
	if len(info.FileInfos) != len(expectedPaths) {
		t.Fatalf("expected %d files, got %d", len(expectedPaths), len(info.FileInfos))
	}

	// Verify sorted paths
	for i, fi := range info.FileInfos {
		if fi.Path != expectedPaths[i] {
			t.Errorf("file[%d].path: expected %q, got %q", i, expectedPaths[i], fi.Path)
		}
	}

	// Verify labels
	if info.Labels["env"] != "prod" {
		t.Errorf("labels[env]: expected prod, got %q", info.Labels["env"])
	}

	// Verify descriptor hashes against Rust reference
	for _, fi := range info.FileInfos {
		expectedHash, ok := expectedDescriptorHashes[fi.Path]
		if !ok {
			t.Errorf("unexpected file in metadata: %s", fi.Path)
			continue
		}
		if fi.DescriptorHash != expectedHash {
			t.Errorf("%s: descriptor hash mismatch\nexpected: %s\ngot:      %s",
				fi.Path, expectedHash, fi.DescriptorHash)
		}
		if err := fi.VerifySelf(); err != nil {
			t.Errorf("%s: VerifySelf failed: %v", fi.Path, err)
		}
	}
}

// TestInterop_BlockLevelRecalculation re-reads the original test files from the fixture
// directory (if present) and recalculates descriptor hashes to ensure consistency.
func TestInterop_BlockLevelRecalculation(t *testing.T) {
	fbPath := filepath.Join(fixtureDir(), "rust.metadata.fb")
	data, err := os.ReadFile(fbPath)
	if err != nil {
		t.Skip("fixture not found — run `make gen-interop-fixture` first")
	}

	info, err := DeserializeMetadata(data)
	if err != nil {
		t.Fatalf("deserialize: %v", err)
	}

	// Check if verity-core/testfiles exists (only in the repo, not in CI testdata)
	testfilesDir := findTestfilesDir(t)
	if testfilesDir == "" {
		t.Skip("testfiles directory not found — this test requires the repo source tree")
	}

	for _, fi := range info.FileInfos {
		filePath := filepath.Join(testfilesDir, fi.Path)
		content, err := os.ReadFile(filePath)
		if err != nil {
			t.Fatalf("read testfile %s: %v", fi.Path, err)
		}

		d := verity.NewFsVerity(verity.HashSHA256)
		d.Write(content)
		desc, tree := d.Finalize()

		recalcHash := hex.EncodeToString(desc.ToDescriptorHash())
		if recalcHash != fi.DescriptorHash {
			t.Errorf("block-level verify failed for %s: expected %s, got %s",
				fi.Path, fi.DescriptorHash, recalcHash)
		}

		rebuiltRoot := tree.RebuildRootHash(desc.Salt, desc.BlockSize())
		if !equalBytes(rebuiltRoot, desc.RootHash) {
			t.Errorf("root hash mismatch for %s", fi.Path)
		}
	}
}

// findTestfilesDir looks for verity-core/testfiles relative to the repo root.
func findTestfilesDir(t *testing.T) string {
	out, err := exec.Command("git", "rev-parse", "--show-toplevel").CombinedOutput()
	if err != nil {
		return ""
	}
	repoRoot := string(bytes.TrimSpace(out))
	dir := filepath.Join(repoRoot, "verity-core", "testfiles")
	if _, err := os.Stat(dir); err == nil {
		return dir
	}
	return ""
}

// TestInterop_CalculateMetadataHash_CrossLanguage loads the Rust-generated metadata
// fixture and verifies that Go's CalculateMetadataHash produces the same root hash
// as Rust's calculate_metadata_hash.
func TestInterop_CalculateMetadataHash_CrossLanguage(t *testing.T) {
	fbPath := filepath.Join(fixtureDir(), "rust.metadata.fb")
	data, err := os.ReadFile(fbPath)
	if err != nil {
		if os.IsNotExist(err) {
			t.Skip("fixture not found — run `make gen-interop-fixture` first")
		}
		t.Fatalf("read fixture: %v", err)
	}

	// Read the expected root hash (committed alongside the fixture)
	hashPath := filepath.Join(fixtureDir(), "rust.metadata.fb.hash")
	expectedHashBytes, err := os.ReadFile(hashPath)
	if err != nil {
		if os.IsNotExist(err) {
			t.Skip("root hash fixture not found — run `make gen-interop-fixture` first")
		}
		t.Fatalf("read root hash fixture: %v", err)
	}
	expectedHash := string(bytes.TrimSpace(expectedHashBytes))

	// Calculate the hash using Go's implementation
	goHash, err := CalculateMetadataHash(data)
	if err != nil {
		t.Fatalf("CalculateMetadataHash: %v", err)
	}

	if goHash != expectedHash {
		t.Errorf("root hash mismatch\nexpected (Rust): %s\ngot (Go):      %s",
			expectedHash, goHash)
	}
}
