// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod cryptpilot {

#[allow(unused_imports, dead_code)]
pub mod verity {


pub enum FsVerityDescriptorOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct FsVerityDescriptor<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for FsVerityDescriptor<'a> {
  type Inner = FsVerityDescriptor<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> FsVerityDescriptor<'a> {
  pub const VT_VERSION: ::flatbuffers::VOffsetT = 4;
  pub const VT_HASH_ALGORITHM: ::flatbuffers::VOffsetT = 6;
  pub const VT_LOG_BLOCKSIZE: ::flatbuffers::VOffsetT = 8;
  pub const VT_DATA_SIZE: ::flatbuffers::VOffsetT = 10;
  pub const VT_ROOT_HASH: ::flatbuffers::VOffsetT = 12;
  pub const VT_SALT: ::flatbuffers::VOffsetT = 14;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    FsVerityDescriptor { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args FsVerityDescriptorArgs<'args>
  ) -> ::flatbuffers::WIPOffset<FsVerityDescriptor<'bldr>> {
    let mut builder = FsVerityDescriptorBuilder::new(_fbb);
    builder.add_data_size(args.data_size);
    if let Some(x) = args.salt { builder.add_salt(x); }
    if let Some(x) = args.root_hash { builder.add_root_hash(x); }
    builder.add_log_blocksize(args.log_blocksize);
    builder.add_hash_algorithm(args.hash_algorithm);
    builder.add_version(args.version);
    builder.finish()
  }


  #[inline]
  pub fn version(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(FsVerityDescriptor::VT_VERSION, Some(0)).unwrap()}
  }
  #[inline]
  pub fn hash_algorithm(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(FsVerityDescriptor::VT_HASH_ALGORITHM, Some(0)).unwrap()}
  }
  #[inline]
  pub fn log_blocksize(&self) -> u8 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u8>(FsVerityDescriptor::VT_LOG_BLOCKSIZE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn data_size(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(FsVerityDescriptor::VT_DATA_SIZE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn root_hash(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(FsVerityDescriptor::VT_ROOT_HASH, None)}
  }
  #[inline]
  pub fn salt(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(FsVerityDescriptor::VT_SALT, None)}
  }
}

impl ::flatbuffers::Verifiable for FsVerityDescriptor<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u8>("version", Self::VT_VERSION, false)?
     .visit_field::<u8>("hash_algorithm", Self::VT_HASH_ALGORITHM, false)?
     .visit_field::<u8>("log_blocksize", Self::VT_LOG_BLOCKSIZE, false)?
     .visit_field::<u64>("data_size", Self::VT_DATA_SIZE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("root_hash", Self::VT_ROOT_HASH, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("salt", Self::VT_SALT, false)?
     .finish();
    Ok(())
  }
}
pub struct FsVerityDescriptorArgs<'a> {
    pub version: u8,
    pub hash_algorithm: u8,
    pub log_blocksize: u8,
    pub data_size: u64,
    pub root_hash: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub salt: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
}
impl<'a> Default for FsVerityDescriptorArgs<'a> {
  #[inline]
  fn default() -> Self {
    FsVerityDescriptorArgs {
      version: 0,
      hash_algorithm: 0,
      log_blocksize: 0,
      data_size: 0,
      root_hash: None,
      salt: None,
    }
  }
}

pub struct FsVerityDescriptorBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> FsVerityDescriptorBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_version(&mut self, version: u8) {
    self.fbb_.push_slot::<u8>(FsVerityDescriptor::VT_VERSION, version, 0);
  }
  #[inline]
  pub fn add_hash_algorithm(&mut self, hash_algorithm: u8) {
    self.fbb_.push_slot::<u8>(FsVerityDescriptor::VT_HASH_ALGORITHM, hash_algorithm, 0);
  }
  #[inline]
  pub fn add_log_blocksize(&mut self, log_blocksize: u8) {
    self.fbb_.push_slot::<u8>(FsVerityDescriptor::VT_LOG_BLOCKSIZE, log_blocksize, 0);
  }
  #[inline]
  pub fn add_data_size(&mut self, data_size: u64) {
    self.fbb_.push_slot::<u64>(FsVerityDescriptor::VT_DATA_SIZE, data_size, 0);
  }
  #[inline]
  pub fn add_root_hash(&mut self, root_hash: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(FsVerityDescriptor::VT_ROOT_HASH, root_hash);
  }
  #[inline]
  pub fn add_salt(&mut self, salt: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(FsVerityDescriptor::VT_SALT, salt);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> FsVerityDescriptorBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    FsVerityDescriptorBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<FsVerityDescriptor<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for FsVerityDescriptor<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("FsVerityDescriptor");
      ds.field("version", &self.version());
      ds.field("hash_algorithm", &self.hash_algorithm());
      ds.field("log_blocksize", &self.log_blocksize());
      ds.field("data_size", &self.data_size());
      ds.field("root_hash", &self.root_hash());
      ds.field("salt", &self.salt());
      ds.finish()
  }
}
pub enum FileInfoOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct FileInfo<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for FileInfo<'a> {
  type Inner = FileInfo<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> FileInfo<'a> {
  pub const VT_PATH: ::flatbuffers::VOffsetT = 4;
  pub const VT_DESCRIPTOR: ::flatbuffers::VOffsetT = 6;
  pub const VT_MERKLE_TREE_LEVEL1: ::flatbuffers::VOffsetT = 8;
  pub const VT_DESCRIPTOR_HASH: ::flatbuffers::VOffsetT = 10;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    FileInfo { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args FileInfoArgs<'args>
  ) -> ::flatbuffers::WIPOffset<FileInfo<'bldr>> {
    let mut builder = FileInfoBuilder::new(_fbb);
    if let Some(x) = args.descriptor_hash { builder.add_descriptor_hash(x); }
    if let Some(x) = args.merkle_tree_level1 { builder.add_merkle_tree_level1(x); }
    if let Some(x) = args.descriptor { builder.add_descriptor(x); }
    if let Some(x) = args.path { builder.add_path(x); }
    builder.finish()
  }


  #[inline]
  pub fn path(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(FileInfo::VT_PATH, None)}
  }
  #[inline]
  pub fn descriptor(&self) -> Option<FsVerityDescriptor<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<FsVerityDescriptor>>(FileInfo::VT_DESCRIPTOR, None)}
  }
  #[inline]
  pub fn merkle_tree_level1(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(FileInfo::VT_MERKLE_TREE_LEVEL1, None)}
  }
  #[inline]
  pub fn descriptor_hash(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(FileInfo::VT_DESCRIPTOR_HASH, None)}
  }
}

impl ::flatbuffers::Verifiable for FileInfo<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("path", Self::VT_PATH, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<FsVerityDescriptor>>("descriptor", Self::VT_DESCRIPTOR, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("merkle_tree_level1", Self::VT_MERKLE_TREE_LEVEL1, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("descriptor_hash", Self::VT_DESCRIPTOR_HASH, false)?
     .finish();
    Ok(())
  }
}
pub struct FileInfoArgs<'a> {
    pub path: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub descriptor: Option<::flatbuffers::WIPOffset<FsVerityDescriptor<'a>>>,
    pub merkle_tree_level1: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub descriptor_hash: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for FileInfoArgs<'a> {
  #[inline]
  fn default() -> Self {
    FileInfoArgs {
      path: None,
      descriptor: None,
      merkle_tree_level1: None,
      descriptor_hash: None,
    }
  }
}

pub struct FileInfoBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> FileInfoBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_path(&mut self, path: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(FileInfo::VT_PATH, path);
  }
  #[inline]
  pub fn add_descriptor(&mut self, descriptor: ::flatbuffers::WIPOffset<FsVerityDescriptor<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<FsVerityDescriptor>>(FileInfo::VT_DESCRIPTOR, descriptor);
  }
  #[inline]
  pub fn add_merkle_tree_level1(&mut self, merkle_tree_level1: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(FileInfo::VT_MERKLE_TREE_LEVEL1, merkle_tree_level1);
  }
  #[inline]
  pub fn add_descriptor_hash(&mut self, descriptor_hash: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(FileInfo::VT_DESCRIPTOR_HASH, descriptor_hash);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> FileInfoBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    FileInfoBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<FileInfo<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for FileInfo<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("FileInfo");
      ds.field("path", &self.path());
      ds.field("descriptor", &self.descriptor());
      ds.field("merkle_tree_level1", &self.merkle_tree_level1());
      ds.field("descriptor_hash", &self.descriptor_hash());
      ds.finish()
  }
}
pub enum MetadataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Metadata<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Metadata<'a> {
  type Inner = Metadata<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Metadata<'a> {
  pub const VT_FILES: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Metadata { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args MetadataArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Metadata<'bldr>> {
    let mut builder = MetadataBuilder::new(_fbb);
    if let Some(x) = args.files { builder.add_files(x); }
    builder.finish()
  }


  #[inline]
  pub fn files(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<FileInfo<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<FileInfo>>>>(Metadata::VT_FILES, None)}
  }
}

impl ::flatbuffers::Verifiable for Metadata<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<FileInfo>>>>("files", Self::VT_FILES, false)?
     .finish();
    Ok(())
  }
}
pub struct MetadataArgs<'a> {
    pub files: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<FileInfo<'a>>>>>,
}
impl<'a> Default for MetadataArgs<'a> {
  #[inline]
  fn default() -> Self {
    MetadataArgs {
      files: None,
    }
  }
}

pub struct MetadataBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> MetadataBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_files(&mut self, files: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<FileInfo<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Metadata::VT_FILES, files);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> MetadataBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    MetadataBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Metadata<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Metadata<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Metadata");
      ds.field("files", &self.files());
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Metadata`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_metadata_unchecked`.
pub fn root_as_metadata(buf: &[u8]) -> Result<Metadata<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<Metadata>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Metadata` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_metadata_unchecked`.
pub fn size_prefixed_root_as_metadata(buf: &[u8]) -> Result<Metadata<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<Metadata>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Metadata` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_metadata_unchecked`.
pub fn root_as_metadata_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Metadata<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<Metadata<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Metadata` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_metadata_unchecked`.
pub fn size_prefixed_root_as_metadata_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Metadata<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<Metadata<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Metadata and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Metadata`.
pub unsafe fn root_as_metadata_unchecked(buf: &[u8]) -> Metadata<'_> {
  unsafe { ::flatbuffers::root_unchecked::<Metadata>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Metadata and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Metadata`.
pub unsafe fn size_prefixed_root_as_metadata_unchecked(buf: &[u8]) -> Metadata<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Metadata>(buf) }
}
#[inline]
pub fn finish_metadata_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<Metadata<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_metadata_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<Metadata<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod verity
}  // pub mod cryptpilot

